---
dist: focal
language: python
python:
  - "3.7"
addons:
  apt:
    packages:
      - yamllint
install:
  - pip install -r requirements.txt
script:
  - find -name "*.yml" -exec yamllint -s {} \;
  - find -name "*.yaml" -exec yamllint -s {} \;
  - ./gen_anki_deck
