#!/usr/bin/env python3
"""
Generate Anki deck with Swahili vocabulary based on the words in
words.yaml.
"""

import random
import yaml

import genanki

from common import get_audio
from models import VOCAB_REVERSE


class VocabNote(genanki.Note):
    """
    The Swahili audio shouldn't influence the GUID
    """

    @property
    def guid(self):
        return genanki.guid_for(self.fields[0], self.fields[1])


def main():
    """
    Generate Anki deck
    """

    deck = genanki.Deck(1597659028800, "Swahili Vocabulary")

    output = "swahili-vocabulary.apkg"
    swahili = genanki.Package(deck)
    with open("words.yaml") as word_file:
        words = list(yaml.load_all(word_file, Loader=yaml.SafeLoader))
        random.shuffle(words)
        for word in words:
            audio = get_audio(word["Swahili"])
            if audio:
                swahili.media_files.append(audio)
                audio = f"[sound:{audio.name}]"
            note = VocabNote(
                model=VOCAB_REVERSE,
                fields=[word["Swahili"], word["English"], audio],
                tags=word.get("Tags"),
            )
            deck.add_note(note)
    swahili.write_to_file(output)
    print(f"Created deck with {len(deck.notes)} notes")


if __name__ == "__main__":
    main()
