on:
  - push
  - pull_request
jobs:
  checks:
    name: Sanity checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
      - run: find -name "*.yaml" -exec yamllint -s {} \;
      - run: python gen_anki_grammar
      - run: python gen_anki_vocabulary
